capturePostgres is the default function
It must be equivalent to require import:

```js
var capturePostgres = require('aws-xray-sdk-postgres');
```

I get this error when try to follow the type definition of this package with TypeScript

```ts
import { capturePostgres } from "aws-xray-sdk-postgres";
```

Then I get this error:

```sh
TypeError: (0 , external_aws_xray_sdk_postgres_namespaceObject.capturePostgres) is not a function
```